syntax = "proto3";

package auth.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service AuthService {
	rpc Register (RegisterRequest) returns (RegisterResponse);
	rpc Login (LoginRequest) returns (LoginResponse);
	rpc Logout (LogoutRequest) returns (google.protobuf.Empty);
	rpc Refresh (RefreshRequest) returns (RefreshResponse);
	rpc RevokeSession (RevokeSessionRequest) returns (google.protobuf.Empty);
	rpc DeleteAccount (DeleteAccountRequest) returns (google.protobuf.Empty);

	rpc ChangePassword (ChangePasswordRequest) returns (google.protobuf.Empty);
	rpc ChangeEmail (ChangeEmailRequest) returns (google.protobuf.Empty);
	rpc ChangePhone (ChangePhoneRequest) returns (google.protobuf.Empty);

	rpc GetSessions (GetSessionsRequest) returns (GetSessionsResponse);
}

message LogoutRequest { }

message TokenPairResponse {
	string accessToken = 1;
	string refreshToken = 2;
}

message RegisterRequest {
	string email = 1;
	string password = 2;
	string deviceIdentifier = 3;
}

message RegisterResponse {
    TokenPairResponse tokenPair = 1;
}

message LoginRequest {
	string login = 1;
	string password = 2;
	string deviceIdentifier = 3;
}

message LoginResponse {
	TokenPairResponse tokenPair = 1;
}

message RefreshRequest {
  string refreshToken = 1;
}

message RefreshResponse {
	TokenPairResponse tokenPair = 1;
}

message RevokeSessionRequest {
	string accountId = 1;
	string deviceIdentifier = 2;
}

message DeleteAccountRequest {
  	optional string id = 1;
}

message SessionData {
	string id = 1;
	string deviceIdentifier = 2;
	google.protobuf.Timestamp expiresAt = 3;
	google.protobuf.Timestamp createdAt = 4;
}

message GetSessionsRequest {
	optional string accountId = 1;
}

message GetSessionsResponse {
	repeated SessionData sessions = 1;
}

message ChangePasswordRequest {
	string accountId = 1;
	string oldPassword = 2;
	string newPassword = 3;
}

message ChangePhoneRequest {
	string accountId = 1;
	string newPhone = 2;
}
