syntax = "proto3";

package user.v1;

import "google/protobuf/empty.proto";

service UserService {
	rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
  	rpc GetUser (GetUserRequest) returns (GetUserResponse);
  	rpc GetUsers (GetUsersRequest) returns (GetUsersResponse);
  	rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
	rpc DeleteUser (DeleteUserRequest) returns (google.protobuf.Empty);
}

message UserProfileData {
	string firstName = 1;
	string lastName = 2;
	uint32 age = 3;
	string bio = 4;
}

message CreateUserRequest {
	UserProfileData userProfile = 1;
}

message CreateUserResponse {
	UserProfileData userProfile = 1;
}

message GetUserRequest {
  	string id = 1;
}

message GetUserResponse {
	UserProfileData userProfile = 1;
}

message GetUsersRequest {
  	uint32 limit = 1;
  	uint32 page = 2;
}

message GetUsersResponse {
	repeated UserProfileData users = 1;
	uint32 total = 2;
	uint32 page = 3;
	uint32 limit = 4;
}

message UpdateUserRequest {
	optional string firstName = 1;
	optional string lastName = 2;
	optional uint32 age = 3;
	optional string bio = 4;
}

message UpdateUserResponse {
	UserProfileData userProfile = 1;
}

message DeleteUserRequest {
	string id = 1;
}
