import { defineConfig } from 'tsup';

export default defineConfig({
	entry: [
		'index.ts',
		'configs/index.ts',
		'filters/index.ts',
		'enums/index.ts',
		'modules/config/index.ts',
		'modules/prisma/index.ts',
		'modules/redis/index.ts',
		'contracts/generated/auth.ts',
		'contracts/generated/token.ts',
		'contracts/generated/user.ts',
		'contracts/generated/google/protobuf/empty.ts',
		'contracts/generated/google/protobuf/timestamp.ts',
	],
	format: ['esm'],
	target: 'es2022',
	platform: 'node',
	splitting: false,
	sourcemap: true,
	clean: true,
	dts: false,
	treeshake: false,
	keepNames: true,
	external: [
		'@nestjs/common',
		'@nestjs/core',
		'@nestjs/config',
		'@nestjs/microservices',
		'@nestjs/swagger',
		'@grpc/grpc-js',
		'@grpc/proto-loader',
		'grpc-health-check',
		'@prisma/client',
		'@prisma/client/runtime/client',
		'reflect-metadata',
		'rxjs',
		'ioredis',
		'joi',
		'node:url',
	],
});
