apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-config
    namespace: backend
data:
    GRPC_HOST: '0.0.0.0'
    HOST: '0.0.0.0'
    PORT: '3001'
    CORS_ORIGIN: 'http://localhost:3000'
    AUTH_SERVICE_URL: 'auth-service:50002'
    USER_SERVICE_URL: 'user-service:50051'
    TOKEN_SERVICE_URL: 'token-service:50004'
    REDIS_HOST: 'redis'
    REDIS_PORT: '6379'
    POSTGRES_HOST: 'postgres'
    POSTGRES_PORT: '5432'
    EXP_DAYS: '30'
    JWT_ISSUER: 'token-service'
    RESET_INTERVAL_MINUTES: '10'