export const AUTH_PACKAGE = 'AUTH_PACKAGE';
export const USER_PACKAGE = 'USER_PACKAGE';
export const TOKEN_PACKAGE = 'TOKEN_PACKAGE';
export const DEFAULT_ROLE_ID = 1;
export const GRPC_HEALTH_STATUS_SERVING = 1;
export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 10;
export const TOKEN_CREATION_ERROR = 'Failed to create access and refresh tokens';
export const API_VERSION = '1.0';
